server:
  port: 9101
  
turbine:
  appConfig: microcloud-dept-hystrix,microcloud-dept
  aggregator:
    clusterConfig: default
  cluster-name-expression: "'default'"
 # clusterNameExpression: new String("default")

spring: 
  application:
    name: microcloud-turbine-9101

    
eureka:
  client:
    service-url:
      defaultZone: http://mxdEureka:mxdEureka@eureka7001.com:7001/eureka/,http://mxdEureka:mxdEureka@eureka7002.com:7002/eureka/,http://mxdEureka:mxdEureka@eureka7003.com:7003/eureka/
  instance:
    instance-id: microcloud-turbine-9101  #自定义服务名字
    prefer-ip-address: true         #访问路径显示IP