server:
  port: 8003
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hdu.springCloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  #http://java:java@dept8003.com:8003/dept/list
spring:
  security:
    user:
      name: Java
      password: mixiaodong
  application:
    name: microcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
eureka:
  client:
    service-url:
      defaultZone: http://mxdEureka:mxdEureka@eureka7001.com:7001/eureka/,http://mxdEureka:mxdEureka@eureka7002.com:7002/eureka/,http://mxdEureka:mxdEureka@eureka7003.com:7003/eureka/
  instance:
    instance-id: microcloud-dept8003  #自定义服务名字
    prefer-ip-address: true         #访问路径显示IP
    
    

info:
  app.name: MiXiaoDong-microcloud
  company.name: www.hdu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$