server:
  port: 80

feign:
  hystrix:
    enabled: true
  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://mxdEureka:mxdEureka@eureka7001.com:7001/eureka/,http://mxdEureka:mxdEureka@eureka7002.com:7002/eureka/,http://mxdEureka:mxdEureka@eureka7003.com:7003/eureka/