server:
  port: 7001

spring: 
  security: 
    user: 
      name: mxdEureka
      password: mxdEureka
  
eureka: 
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名
  client: 
    register-with-eureka: false #false表示不向eureka注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:              #以下密码必加
      defaultZone: http://mxdEureka:mxdEureka@eureka7002.com:7002/eureka/,http://mxdEureka:mxdEureka@eureka7003.com:7003/eureka/  #设置与eureka server交互的地址查询服务和注册都需要依赖的地址
      
  server:
    peer-node-read-timeout-ms: 90000    #那个节点出现 Read timed out。只需要加上这句话即可解决

